name: CI/CD Pipeline

on:
  push:
    branches:
      - docker   # trigger only when docker branch is pushed
  workflow_dispatch: 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: print secrets
        run: echo "aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} and ${{ secrets.AWS_SECRET_ACCESS_KEY }}"
